apiVersion: v1
kind: Pod
metadata:
  name: "nginx-configmap"
  labels:
    app: cos
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    ports:
    - containerPort: 80
    # args:
    # - /bin/sh
    # - -c
    # - touch /tmp/healthy; sleep 16; rm -rf /tmp/healthy; sleep 3600
    readinessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
      failureThreshold: 2
    # livenessProbe:
    #   exec:
    #     command:
    #     - cat
    #     - /tmp/healthy
    #   initialDelaySeconds: 5
    #   periodSeconds: 5
    #   failureThreshold: 2
    startupProbe:
      exec:
        command:
        - curl
        - localhost
      initialDelaySeconds: 5
      periodSeconds: 5
      failureThreshold: 2
      # httpGet:
      #   path: /healthz
      #   port: 80
      # initialDelaySeconds: 5
      # periodSeconds: 5
      # failureThreshold: 3

  
