apiVersion: apps/v1
kind: Deployment
metadata:
  name:  deploy-example
spec:
  replicas: 4
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: contra
  template:
    metadata:
      labels:
        app:  contra
    spec:
      containers:
      - name:  nginx
        image:  nginx:alpine
        ports:
        - containerPort:  80
 