apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mydeployment
  namespace: wypociny
  labels:
    app: mywebapp
spec:
  selector:
    matchLabels:
        app: mywebapp
        tier: frontend
  replicas: 5
  template:
    metadata:
      labels:
        app: mywebapp
        tier: frontend
    spec:
      containers:
      - name: mycontainer
        image: devopsjourney1/mywebapp:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: myconfigmapa
        resources:
            requests:
                memory: "16Mi"
                cpu: "50m"
            limits:
                memory: "128Mi"
                cpu: "100"

