apiVersion: v1
kind: Service
metadata:
  name: mywebapp
  namespace: wypociny
  labels:
    app: mywebapp
spec:
  
  ports:
  - port: 80
    # targetPort: 
    protocol: TCP
    name: flask
  selector:
    app: mywebapp
    tier: frontend
  type: NodePort